### ISSUE TITLE
Question: Rate limiting defaults without your library

### ISSUE THREAD

**Issue by hellofunk** [myfreeweb/ring-ratelimit#2]
I'm curious if you can advise where this library fits into the default functionality provided by Ring. I assume that by offering this library, Ring must not by default do any rate limiting at all... is this correct? So Ring would just process as many requests that it can handle without throttling... unless I use a library like yours. Is that an accurate interpretation? It was suggested to me elsewhere that Jetty might already be rate limiting by default.

**Comment by myfreeweb** [comment]
Ring by itself does not do anything, it's a spec that defines a key-value mapping ;-)

I don't know what Jetty does. I used to use http-kit, but I haven't touched anything Clojure related in a long time. Anyway, the library allows much more advanced stuff, integrated with your app logic, such as per user limits, etc.
